### ISSUE TITLE
子域名更新的问题

### ISSUE THREAD

**Issue by svkoh** [yyqian/aliyun-ddns#1]
使用时发现更新子域名时会出错 `"Code":"IncorrectDomainUser","Message":"The domain name does not belong to this  user."`，下面是我的解决办法:

因为有多级子域名，所以 `RR` 的获取方式改为
```
target.hostname.split('.').slice(0, -2).join('.')
```
`DomainName` 的获取方式改为
```
target.hostname.split('.').slice(-2).join('.')
```

更新子域名时，`describeParams` 要使用
```
const describeParams = {              
  Action: 'DescribeSubDomainRecords', 
  SubDomain: target.hostname          
};                                    
```

**Comment by yyqian** [comment]
感谢提交 Bug，已经 fix 了：
https://github.com/yyqian/aliyun-ddns/commit/19b7d9c2e230ab2ebd12a3bd14be9dcb6d089bda
