### ISSUE TITLE
路由器 pandorabox 这个要怎么弄?

### ISSUE THREAD

**Issue by xman55555** [yyqian/aliyun-ddns#12]
是不是必须 要求 node.js 环境才能用? 还有就是 server-mode这个模式没搞懂是怎么使用的,感觉应该用客户端就可以了吧?
为什么还要用服务端?

**Comment by yyqian** [comment]
client-mode 必须要node.js 环境，推荐用这个
server-mode 相当于客户端只是ping下服务端，服务端知道了客户端的IP，接着去update域名信息
