### ISSUE TITLE
按照说明配置后运行报错

### ISSUE THREAD

**Issue by 0whale0** [yyqian/aliyun-ddns#6]
按照说明配置后提示错误，就没有了，麻烦问一下这个有日志吗？
![image](https://user-images.githubusercontent.com/37136826/47839854-3b808200-ddef-11e8-94fc-7271f2d62fa1.png)

![image](https://user-images.githubusercontent.com/37136826/47839792-fa886d80-ddee-11e8-885d-6d70dd3ee5cb.png)

**Comment by yyqian** [comment]
错误信息都吞掉了，你可以自己在 alidns.js lines 148, 160 打日志看错误内容
