### ISSUE TITLE
讨论 Server 多余性问题

### ISSUE THREAD

**Issue by caryyu** [yyqian/aliyun-ddns#8]
我的理解是只需要客户端调用阿里云的 API 修改 DNS 解析即可，为什么还要 Server，请帮忙解惑一下，可能我忽略了某些细节，谢谢！

**Comment by yyqian** [comment]
我写过两个版本，新版的是在客户端实现所有逻辑的，不需要server端，唯一缺点就是客户端需要 node.js 环境，不太适合在一些路由器设备上。

旧版的客户端只是执行一个类似 curl 的命令，逻辑都是在 server 端实现，包括获取客户端的公网 IP 地址，但这个实际存在潜在的 security 问题，优点只是对客户端环境要求低一点
