### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by wenjinghuan999** [yyqian/aliyun-ddns#9]
可否添加支持AAAA记录的功能？

**Comment by wenjinghuan999** [comment]
给想自己手动改的人一个参考吧（虽然很简单就是了）

- alidns.js中的两个Type改为AAAA
- app.js中
  - simpleGetPubIpUrl可以用‘v6.ident.me’，去掉原有的
  - isValidIp直接返回true（懒得自己写正则表达式了）
  - pubIpApi中去掉apiList[simpleGetPubIpUrl.length] = taobaoApi;

**Comment by yyqian** [comment]
Thx for the suggestion and workaround, will keep it as is for now. Support in the future
